name: Build

on:
  push:
    branches: [dev]
  workflow_dispatch:

env:
  RETENTION: 7

jobs:
  build-windows:
    name: Windows build
    strategy:
      matrix:
        arch: [arm64]
    runs-on: ${{ matrix.arch == 'arm64' && 'windows-11-arm' || 'windows-latest' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build
        #shell: cmd
        run: |


          cmake -S . -B build -G Ninja -DCMAKE_SYSTEM_PROCESSOR=ARM64 -DMCL_MSM=OFF -DCMAKE_CXX_COMPILER=clang++
          cmake --build build --config Release
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: win-${{ matrix.arch }}
      #     path: build/bin/release/mcl.dll
      #     retention-days: ${{ env.RETENTION }}
      #     if-no-files-found: error
