name: Build

on:
  push:
    branches: [arm64]
  workflow_dispatch:

env:
  RETENTION: 7

jobs:
  build-windows:
    name: Windows build
    strategy:
      matrix:
        arch: [x64]
    runs-on: ${{ matrix.arch == 'arm64' && 'windows-11-arm' || 'windows-latest' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          "${env:ProgramFiles}/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsamd64_arm64.bat"
          cmake -S . -B build -G "Ninja" `
            -DCMAKE_SYSTEM_NAME=Windows `
            -DCMAKE_SYSTEM_PROCESSOR=ARM64 `
            -DCMAKE_C_COMPILER="${env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\bin\clang-cl.exe" `
            -DCMAKE_CXX_COMPILER="${env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\bin\clang-cl.exe" `
            -DCMAKE_C_FLAGS="--target=arm64-windows" `
            -DCMAKE_CXX_FLAGS="--target=arm64-windows"
          cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-${{ matrix.arch }}
          path: bin/mcl.dll
          retention-days: ${{ env.RETENTION }}
          if-no-files-found: error
