name: Build

on:
  push:
    branches: [dev]
  workflow_dispatch:

env:
  RETENTION: 7

jobs:
  build-windows:
    name: Windows build
    strategy:
      matrix:
        arch: [arm64]
    runs-on: ${{ matrix.arch == 'arm64' && 'windows-11-arm' || 'windows-latest' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build
        shell: cmd
        run: |
          # $ml64Pattern = "${env:ProgramFiles}/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/*/bin/Hostx64/x64/ml64.exe"
          # $ml64Path = Get-ChildItem -Path $ml64Pattern -ErrorAction SilentlyContinue | Sort-Object | Select-Object -Last 1

          # if ($ml64Path) {
          #   Write-Host "Found MASM: $ml64Path"
          #   $env:PATH = "$($ml64Path.Directory.FullName);$env:PATH"
          # } else {
          #   Write-Error "MASM not found"
          # }

          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsamd64_arm64.bat" ^
          && clang++ --target=arm64-pc-windows src\fp.cpp src\base64.ll src\bint64.ll test\bls12_test.cpp -I include -I src -DMCL_MSM=0 -o bls12_test.exe

          # cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_SHARED_LINKER_FLAGS="/Brepro"
          # cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-${{ matrix.arch }}
          path: build/bin/release/mcl.dll
          retention-days: ${{ env.RETENTION }}
          if-no-files-found: error
