name: Build

on:
  push:
    branches: [dev]
  workflow_dispatch:

env:
  RETENTION: 7

jobs:
  build-windows:
    name: Windows build
    strategy:
      matrix:
        arch: [arm64]
    runs-on: ${{ matrix.arch == 'arm64' && 'windows-11-arm' || 'windows-latest' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build
        shell: cmd
        run: |


          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsamd64_arm64.bat" ^
          cmake -S . -B build -G "Ninja" ^
          -DCMAKE_SYSTEM_NAME=Windows ^
          -DCMAKE_SYSTEM_PROCESSOR=ARM64 ^
          -DCMAKE_C_COMPILER="C:/Program Files/LLVM/bin/clang.exe" ^
          -DCMAKE_CXX_COMPILER="C:/Program Files/LLVM/bin/clang++.exe" ^
          -DCMAKE_LINKER="C:/Program Files/LLVM/bin/lld-link.exe" ^
          -DCMAKE_C_FLAGS="--target=arm64-windows -fuse-ld=lld" ^
          -DCMAKE_CXX_FLAGS="--target=arm64-windows -fuse-ld=lld" ^
          -DCMAKE_EXE_LINKER_FLAGS="/subsystem:console"
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: win-${{ matrix.arch }}
      #     path: build/bin/release/mcl.dll
      #     retention-days: ${{ env.RETENTION }}
      #     if-no-files-found: error
