name: Build

on:
  push:
    branches: [arm64]
  workflow_dispatch:

env:
  RETENTION: 7

jobs:
  build-windows:
    name: Windows build
    strategy:
      matrix:
        arch: [x64]
    runs-on: ${{ matrix.arch == 'arm64' && 'windows-11-arm' || 'windows-latest' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build
        shell: cmd
        run: |


          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsamd64_arm64.bat"
          mklib_arm64 dll
          mk_arm64 -d test\bn_c384_256_test.cpp
          mk_arm64 -s test\bls12_test.cpp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-${{ matrix.arch }}
          path: bin
          retention-days: ${{ env.RETENTION }}
          if-no-files-found: error
