name: Build

on:
  push:
    branches: [dev]
  workflow_dispatch:

env:
  RETENTION: 7

jobs:
  build-windows:
    name: Windows build
    strategy:
      matrix:
        arch: [arm64]
    runs-on: ${{ matrix.arch == 'arm64' && 'windows-11-arm' || 'windows-latest' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Clang Tools for Visual Studio
        run: |
          # Path to Visual Studio Installer
          $vsInstaller = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vs_installer.exe"

          # Install Clang tools for MSVC (ID: Microsoft.VisualStudio.Component.VC.Llvm.Clang)
          & $vsInstaller modify --quiet --norestart `
            --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" `
            --add Microsoft.VisualStudio.Component.VC.Llvm.Clang

      - name: Build
        shell: cmd
        run: |


          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsamd64_arm64.bat" ^
          && cmake -S . -B build -G "Visual Studio 17 2022" -A arm64 -DMCL_MSM=OFF -DCMAKE_CXX_COMPILER=clang-cl ^
          && cmake --build build --config Release
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: win-${{ matrix.arch }}
      #     path: build/bin/release/mcl.dll
      #     retention-days: ${{ env.RETENTION }}
      #     if-no-files-found: error
