name: Build

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  RETENTION: 7

jobs:
  build-windows:
    name: Windows build
    strategy:
      matrix:
        arch: [x64]
    runs-on: ${{ matrix.arch == 'arm64' && 'windows-11-arm' || 'windows-latest' }}
    steps:
      - name: Disable line ending conversion
        run: git config --global core.autocrlf input

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.arch == 'arm64' && 'clangarm64' || 'clang64' }}
          install: >-
            base-devel git libtool cmake mingw-w64-x86_64-gmp mingw-w64-x86_64-ninja mingw-w64-x86_64-gcc
            ${{ matrix.arch == 'arm64' && 'mingw-w64-clang-aarch64-toolchain' || 'mingw-w64-clang-x86_64-toolchain' }}

      - name: Build
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_PREFIX_PATH=/mingw64 -DCMAKE_CXX_COMPILER=clang++
          make
          ls .

      # - name: Build
      #   shell: pwsh
      #   run: |
      #     # mkdir build
      #     # cd build
      #     cmake -S . -B build -G "Visual Studio 17 2022" -A x64
      #     cmake --build build --config Release
      #     ls .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-${{ matrix.arch }}
          path: build
          retention-days: ${{ env.RETENTION }}
          if-no-files-found: error
